ssp_analytics:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DATABASE_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer
      database: analytics
      warehouse: developer_wh
      schema: public
      threads: 1
    prod:
      type: snowflake
      account: "{{ env_var('DATABASE_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: automation
      database: analytics
      warehouse: automation_wh
      schema: public
      threads: 1
    ci:
      type: snowflake
      account: "{{ env_var('DATABASE_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: automation
      database: analytics
      warehouse: automation_wh
      schema: public
      threads: 1
  target: dev